### ISSUE TITLE
Support for React.createRef() refs passed to innerRef

### ISSUE THREAD

**Issue by Carnewal** [buildo/react-autosize-textarea#102]
React has a new way of creating refs; https://reactjs.org/docs/refs-and-the-dom.html

When passing a createRef()'d ref to the innerRef prop, an "innerRef is not a function" error is thrown.

**Comment by gausie** [comment]
Using this new export is the solution https://reactjs.org/docs/forwarding-refs.html

**Comment by angelolucas** [comment]
Thanks @gausie, forwarding refs works for me!

```
import TextareaAutosize from 'react-autosize-textarea'

class MyComponent extends Component {
  textareaAutosize = React.createRef()
  
  componentDidMount() {
    this.textareaAutosize.current.textarea.focus()
  }
  
  render() {
    return (
      <TextareaAutosize ref={this.textareaAutosize} />
    )
  }
}
```

**Comment by sirreal** [comment]
@FrancescoCioria Could you elaborate on why this was closed?

**Comment by gnapse** [comment]
@FrancescoCioria I have the same question. Now with hooks this is more salient.

**Comment by FrancescoCioria** [comment]
sorry my mistake, this issue was not supposed to be closed

**Comment by alexlouden** [comment]
Gave this a shot - contributions welcome! #124

**Comment by FrancescoCioria** [comment]
Finally we're supporting the new `React.createRef()` 🎉 
You can give it a shot with `v7.0.0` (I've treated it as a breaking release as React suggests)

**Comment by tommedema** [comment]
I'm still getting this in 7.0.0: https://github.com/buildo/react-autosize-textarea/issues/141
