### ISSUE TITLE
innerRef / inputRef

### ISSUE THREAD

**Issue by kimbylr** [buildo/react-autosize-textarea#112]
In the readme it's stated that I get a reference to the DOM node with `innerRef`:

`<TextareaAutosize innerRef={ref => this.textarea = ref} />`

Isn't the prop called `inputRef` though? – this works for me while `innerRef` doesn't.

**Comment by FrancescoCioria** [comment]
nope, it's `innerRef`, probably you confused this repo with https://github.com/andreypopp/react-textarea-autosize where the prop is indeed `inputRef` :)

**Comment by kimbylr** [comment]
you're so right… sorry about that, i was evaluating different libraries and managed to confuse myself ;)
