### ISSUE TITLE
Bad performance for a controlled component for continuous text updates

### ISSUE THREAD

**Issue by mingyuan-xia** [buildo/react-autosize-textarea#113]
Hi I am having a controlled textarea receiving stdout data from a long-running child_proc running a Python script. The script is producing about 4-5 normal-length lines per second. But I encounter lags after running it for >20minutes (several MB accumulated text). Any suggestion on this? Should I use an uncontrolled component with ref and appending the text manually on the ref?
Any suggestion would be great, thanks.

**Comment by FrancescoCioria** [comment]
Hi @mingyuan-xia 

> Should I use an uncontrolled component with ref and appending the text manually on the ref?

do you have perf issues also with a standard textarea or only when using a `react-autosize-textarea`?
if only when using `react-autosize-textarea`, than the heavy part is probably the resize event. In that case manually appending the text wouldn't make any difference as you'd still need to trigger a resize event to actually resize the textarea.

The only suggestion I can come with is to debounce the resize event to a slower rate (like once per second)...

**Comment by mingyuan-xia** [comment]
thanks, I will profile and have a try

**Comment by mingyuan-xia** [comment]
Solved.
Every time the text is updated. a DOM re-layouting is needed. Two optimizations needed:
1. reduce the text size in the box -> reduce per-re-layouting time (ref. with 1.8MB text a re-layout operation takes ~200ms)
2. consolidate state updates per second (basically reduce how often re-layout kicks in per second)
