### ISSUE TITLE
If passed value to component on its initial render, he does not resize textarea for it.

### ISSUE THREAD

**Issue by pilotocheg** [buildo/react-autosize-textarea#122]
If passed value to the textarea-component on its initial render, he does not resize textarea for it.

**Comment by FrancescoCioria** [comment]
Hi @pilotocheg ,

I'm not experiencing this issue, can you give me more context? can you show me your code?

![image](https://user-images.githubusercontent.com/4029499/51751283-c8686e00-20b4-11e9-9c9f-23e93b0599e5.png)

You can try it yourself in our playground: https://react-components.buildo.io/#textareaautosize

**Comment by FrancescoCioria** [comment]
NOTE: if you're using `styled-components` you need to `async` to `true`, otherwise it will not work at the initial render
