### ISSUE TITLE
Passing a function to ref fails prop type validation

### ISSUE THREAD

**Issue by kislakiruben** [buildo/react-autosize-textarea#130]
I'm passing a function to ref. The callback is called correctly, but I get an error from `TextareaAutosizeClass` saying that `innerRef` should be an object.

```
checkPropTypes.js:19 Warning: Failed prop type: Invalid prop `innerRef` of type `function` supplied to `TextareaAutosizeClass`, expected `object`.
    in TextareaAutosizeClass
```

This is what I'm actually doing:
```jsx
const refs = [];
const updateRefs = (ref) => refs.push(ref);

<TextareaAutosize ref={updateRefs} />
```

**Comment by geosigno** [comment]
+1

**Comment by Aarbel** [comment]
Have you found any solution for this issue ?

**Comment by Aarbel** [comment]
@giogonzo ?

**Comment by Aarbel** [comment]
@FrancescoCioria

**Comment by giogonzo** [comment]
Hi @kislakiruben et al, I'm not able to reproduce this issue using the latest version (`7.0.0`).
Please let me know if this is not the case for you!

**Comment by tommedema** [comment]
Did you find a solution to this? I am experiencing this too: https://github.com/buildo/react-autosize-textarea/issues/141
