### ISSUE TITLE
Ref issue & Compatibility with React 15.4.0

### ISSUE THREAD

**Issue by FrancescoCioria** [buildo/react-autosize-textarea#23]
## description
Since `React15` refs should be used with callbacks

## how to reproduce
- {optional: describe steps to reproduce bug}

## specs
- store `textarea` ref as `this.textarea` with callback
- remove `getTextareaDOMNode`

## misc
{optional: other useful info}

**Comment by pladaria** [comment]
Please, next time release a major version if you introduce breaking changes (like removing a method like getTextareaDOMNode).

**Comment by FrancescoCioria** [comment]
@pladaria I'm sorry that caused you troubles, but this library has officially dropped support for React0.13 several months ago: https://github.com/buildo/react-autosize-textarea/releases/tag/v0.3.0

For React0.14 and React15 that commit is **not** a breaking change therefore it's correct to release a non-major version like a minor or a patch.

If you're still using React0.13 please use 0.2.x versions.
