### ISSUE TITLE
Remove react-tcomb

### ISSUE THREAD

**Issue by eek** [buildo/react-autosize-textarea#30]
One of the issues I currently have is that `react-autosize-textarea` includes `react-tcombe`, and my final **production** build has an extra 53kb just from t-combe.

Can we remove it?

**Comment by giogonzo** [comment]
Hi @eek , the number seems off to me. Are you actually minifying your production bundle?

`tcomb` + `tcomb-react` should amount to about 14Kb when minified, and less than 4Kb when minified and gzipped

**Comment by eek** [comment]
That's an approximation by webpack (with minifying on) so it might be off. 

I don't understand the added value that brings to a library that is 3.7kb. I mean, what's the reason to have something 14 times larger just to check props when React has something built in that's great.

```
export const Props = {
  rows: t.maybe(t.Integer),
  maxRows: t.maybe(t.Integer),
  onResize: t.maybe(t.Function)
};
```

I can do a pull request to fix this if that's ok with you guys as well.

**Comment by giogonzo** [comment]
Yes, I fully agree.
Didn't mean to be the nitpicker here, just wanted to add exact numbers to this conversation :) So here they are (minified): `react-autosize-textarea` 4k, `autosize` 3.5k, `tcomb` 12.5k, `tcomb-validation` 4k .

We've been using `tcomb` up to now mostly for parity with other internal projects and historic reasons.
In our internal projects we are already paying the `tcomb` additional bytes so it hasn't been an issue for us.

We'll gladly accept a PR for this, but it will probably require a few changes cross-repo so it might not be merged & released right away. In any case I'll leave the final word to @FrancescoCioria

**Comment by FrancescoCioria** [comment]
Yes, we can remove it :)
@eek can you open a PR for us?
