### ISSUE TITLE
linked module fails to load in webpack

### ISSUE THREAD

**Issue by georgevs** [buildo/react-autosize-textarea#48]
Hi,

I tried to link the `react-autosize-textarea`  module in my project (npm link) to debug some issue but it failed with the error that `lib` cannot be found. I traced the failure to the `react-autosize-textarea/index.js` where `require()` is called without the leading './' which causes the loader to search for lib in node_modules.  Once the leading './' is added everything seems to work.

**Comment by FrancescoCioria** [comment]
Thank you @georgevs, this is definitely a bug!

I'll fix it right away and improve tests as they should import the built component from `index.js`

**Comment by FrancescoCioria** [comment]
I released `0.4.4` with the fix, thank you for reporting it :)
