### ISSUE TITLE
Textarea is slow on safari

### ISSUE THREAD

**Issue by ascariandrea** [buildo/react-autosize-textarea#52]
## description
The `textarea` input is lagged on Safari.

## how to reproduce
- {optional: describe steps to reproduce defect}

## specs
- debounce `this.dispatchEvent` 

## misc
{optional: other useful info}

**Comment by FrancescoCioria** [comment]
Apparently what is slow in Safari is the layout-reflow when you have a lot of flex views.
If you have a serious problem in performance and you can't easily simplify the layout I suggest to: 
- wrap the textarea
- pass `position: 'relative'` to the wrapper
- pass `position: 'absolute'` to the textarea

It's not elegant, but it should improve performance considerably
