### ISSUE TITLE
Uncaught Error: Module build failed: Error: ENOENT: no such file or directory, 

### ISSUE THREAD

**Issue by hyusetiawan** [buildo/react-autosize-textarea#62]
I am using webpack 2 and this is how I import it:
```
import TextareaAutosize from 'react-autosize-textarea'
```

**Comment by hyusetiawan** [comment]
checking the versions, since 0.3.6 and above, there is no index.js

**Comment by giogonzo** [comment]
Hi @hyusetiawan, there's no `index.js` in the root because the `package.json` says `"main": "lib"` (and there is indeed a `lib/index.js`).

I briefly tried to reproduce the issue on webpack@3 using `react-autosize-textarea@0.4.8`, with no luck. Anything else that could help us reproduce this?

**Comment by hyusetiawan** [comment]
hmm I am not sure, I am using webpack 2 however, will close this as this does not block me anymore (end up using the version with index.js)
