### ISSUE TITLE
Resize component when inner textarea value is cleared

### ISSUE THREAD

**Issue by estill01** [buildo/react-autosize-textarea#67]
Given
```
<TextareAutosize innerRef={c=>{refTextarea=c}} />
<button onClick={clearTextarea}>Clear</button>

...

function clearTextarea() {
  refTextarea.value = ''
}
```

When you click the 'Clear' button, the content of the inner ref textarea is replaced with the empty string, but the height of the outer TextareaAutosize component retains whatever height it had ahead of the content clear.

**Comment by FrancescoCioria** [comment]
Hi @estill01 ,

Why are you changing the value of `TextareAutosize` directly?

`TextareaAutosize` updates its height at every `render` in the `componentDidUpdate`, this way you're changing its `value` outside of the `React`'s lifecycle, therefore `componentDidUpdate` is never called and the height is never updated.

Is there a reason you're not doing the following?

```js
<TextareAutosize value={this.state.value} onChange={(e) => this.setState({ value: e.target.value }) />
<button onClick={clearTextarea}>Clear</button>

...

function clearTextarea() {
  this.setState({ value: '' })
}
```

**Comment by FrancescoCioria** [comment]
I'm closing this, feel free to open a new issue if you think it's still relevant.

**Comment by bmamouri** [comment]
I've got the same issue. In my case the TextArea is not controlled, due to performance reasons. When I update the `value` property of the TextArea, it doesn't fit to accomodate the text. Is there a way to dispatch the resize event manually?

**Comment by FrancescoCioria** [comment]
Disclaimer: I haven't been working on this for a while

There isn't any official API to do that, but I think you could manually import `autosize` (try installing the same version) and then call `autosize.update(textareaRef)` where `textareaRef` is the the value you get from `props.innerRef`.

This is the call that's happening in `componentDidUpdate`: https://github.com/buildo/react-autosize-textarea/blob/master/src/TextareaAutosize.tsx#L159
