### ISSUE TITLE
Version 1.0.0 not found?

### ISSUE THREAD

**Issue by Batistleman** [buildo/react-autosize-textarea#77]
With version 1.0.0 I'm getting: 

    Uncaught (in promise) Error: Cannot find module 'react-autosize-textarea' 

When trying to import the package.

Any ideas?

**Comment by jkudish** [comment]
Same issue here. Looks like the published package doesn't have any built files that can be imported, only the typescript source 😕

**Comment by gabro** [comment]
Thanks for reporting. There's been a mistake on our side, we'll be fixing it in a few minutes!

**Comment by gabro** [comment]
Fixed! Version 1.0.1 should be ok, sorry for the broken release! :)

**Comment by jkudish** [comment]
Thank you for the quick fix!
