### ISSUE TITLE
Missing to publish lib folder to npm?

### ISSUE THREAD

**Issue by rohmanhm** [buildo/react-autosize-textarea#83]
Looks like you are missing to publish `lib` folder to npm.

![image](https://user-images.githubusercontent.com/7524911/33659077-7cd754e6-dab1-11e7-99a2-acbbab7eb23e.png)

The effect is I cannot find declaration file when I import your library.

![image](https://user-images.githubusercontent.com/7524911/33659126-9c448d30-dab1-11e7-89c3-bfae3c150d24.png)

**Comment by FrancescoCioria** [comment]
Hi @rohmanhm, which version are you using?
We fixed this issue in [v1.0.1](https://github.com/buildo/react-autosize-textarea/tree/v1.0.1) and deprecated `v1.0.0`

**Comment by rohmanhm** [comment]
I'm on version v1.0.1

![image](https://user-images.githubusercontent.com/7524911/33697176-352cc93c-db38-11e7-888a-0d5b370f9e51.png)

**Comment by FrancescoCioria** [comment]
> The effect is I cannot find declaration file when I import your library.

Oh sorry, I concentrated on the first sentence. No, the `lib` is indeed published, the problem here is that the `typings` pointer is missing from the `package.json` as reported in #79 

I published `v1.0.2` with the fix, let me know if it fixes the problem for you too.
