### ISSUE TITLE
Is there a way to control Alignment? 

### ISSUE THREAD

**Issue by carpben** [buildo/react-autosize-textarea#90]
I've build an [app](https://next-f2cee.firebaseapp.com/) that uses the component multiple times. Great work! 
I personally use the app with two languages - English, and another language which is aligned to the right. By default the text-areas align to the left. If I want to change and align them to the right I can simply press right CTR+Shift. When the screen re-renders it is aligned to the left again. I want to somehow control the alignment - recognize if a user chooses to align in a certain way, and save it to the state. How can I recognize how the user chooses to align the text, or if he presses right or left CTR+Shift? And how do I change the text-area so the alignment is controlled?

**Comment by FrancescoCioria** [comment]
Hi @carpben and thank you, I'm very happy to hear that you're using our component in you application :)

I'm not sure what CTR+Shift does, but you can force a website to be in "right-to-left" mode by passing `dir="rtl"` to the HTML tag.

If you want to set only TextareaAutosize in "right-to-left" mode you can pass `dir="rtl"` to it:

```js
<TextareaAutosize dir="rtl" />
```

I tested it in our [live demo](http://react-components.buildo.io/#textareaautosize) and it worked great:
![image](https://user-images.githubusercontent.com/4029499/34668041-ed570936-f46b-11e7-84a5-1f4941076d5f.png)
