### ISSUE TITLE
Resize horizontal inline style overrides CSS styles 

### ISSUE THREAD

**Issue by humphreybc** [buildo/react-autosize-textarea#93]
I'm passing `resize: none` through as CSS to disable the drag handle in the bottom right of the textarea, but it's being overridden by an inline style `resize: horizontal`. After a short investigation, I think this is coming from [autosize line 53](https://github.com/jackmoore/autosize/blob/master/src/autosize.js#L53).

Here's some reproduction code:

```jsx
import * as React from "react";
import TextareaAutosize from "react-autosize-textarea";
import { style } from "typestyle";

export class ResizeDemo extends React.PureComponent {
  public render() {
    return <TextareaAutosize className={textAreaClassName} />;
  }
}

const textAreaClassName = style({
  resize: "none"
});

```

**Comment by FrancescoCioria** [comment]
Yes, it does it because it needs to ensure vertical `resize` is disabled.
My guess is you're having this issue because your `style` function adds the style asynchrously so **after** `autosize` has been initialized.

I suggest you pass `resize: "none"` as inline style to fix the problem:

```js
return <TextareaAutosize className={textAreaClassName} style={{ resize: "none" }} />;
```

I tested the code above in our demo environment and it worked fine

**Comment by humphreybc** [comment]
@FrancescoCioria Thanks for your quick reply! Your suggestion works. Cheers!

**Comment by shuji-koike** [comment]
> pass resize: "none" as inline style to fix the problem

Unfortunately, this solution did not work for me 😿 
However, using `styled-components` with `!important` seems to work.

```js
const StyledTextArea = styled(TextareaAutosize)`
  resize: ${props => props.resize} !important;
`
```

ref https://codesandbox.io/s/pensive-kapitsa-owzfy?file=/src/App.tsx

@FrancescoCioria Any idea why "inline style" is not working?
