### ISSUE TITLE
Error after render component.

### ISSUE THREAD

**Issue by dramoturg** [buildo/react-autosize-textarea#99]
Hi. I used component version 3.0.1. After render component on page, console are display  error.
`vendor.js:8748 Warning: Use the "defaultValue" or "value" props instead of setting children on <textarea>.`
React version 15.2.1.

**Comment by FrancescoCioria** [comment]
Hi @dramoturg , that is a common warning of `React`: the feature of passing the value as `children` has been deprecated since `React` 15

In your code you doing something like:

```jsx
<TextareaAutosize>
  your value
</TextareaAutosize>
```

you should replace that with:

```jsx
<TextareaAutosize value="your value" />
```

and the warning should go away

**Comment by dramoturg** [comment]
thanks. it solved the problem
